### PR TITLE
Upload Profile Picture

### PR DESCRIPTION
**Pull request by AbdulRahmanMudasser**
#23 

1. In forms.py, created a class ProfilePictureForm
2. In views.py, created a page options-page
3. In urls.py, created a url for options' page
4. Marked the options' page as login_required
5. Displaying profile at the top left corner

### CODE REVIEW

**Comment by abdullah956** [comment]
@AbdulRahmanMudasser Please write a proper description for the changes you made or added in this PR. 
I found two major bugs :
1) The upload page after uploading the profile do not redirect us back to home.
2) If a user already has profile it was not showing it on the home page.
I fixed these two by makings some changes on views.py and welcome.html.

**Comment by AbdulRahmanMudasser** [comment]
> @AbdulRahmanMudasser Please write a proper description for the changes you made or added in this PR. I found two major bugs :
> 
> 1. The upload page after uploading the profile do not redirect us back to home.
> 2. If a user already has profile it was not showing it on the home page.
>    I fixed these two by makings some changes on views.py and welcome.html.

Why would the user be redirected to the home?

**Comment by abdullah956** [comment]
> > @AbdulRahmanMudasser Please write a proper description for the changes you made or added in this PR. I found two major bugs :
> > 
> > 1. The upload page after uploading the profile do not redirect us back to home.
> > 2. If a user already has profile it was not showing it on the home page.
> >    I fixed these two by makings some changes on views.py and welcome.html.
> 
> Why would the user be redirected to the home?

To see his posts and new profile picture. Is this not what happens when we upload our profile picture on instagram.

**Comment by AbdulRahmanMudasser** [comment]
> > > @AbdulRahmanMudasser Please write a proper description for the changes you made or added in this PR. I found two major bugs :
> > > 
> > > 1. The upload page after uploading the profile do not redirect us back to home.
> > > 2. If a user already has profile it was not showing it on the home page.
> > >    I fixed these two by makings some changes on views.py and welcome.html.
> > 
> > 
> > Why would the user be redirected to the home?
> 
> To see his posts and new profile picture. Is this not what happens when we upload our profile picture on instagram.

When we upload a profile picture, we are redirected to the profile page, not the home page. There is a difference between the home page and the profile page.

**Comment by abdullah956** [comment]
> > > > @AbdulRahmanMudasser Please write a proper description for the changes you made or added in this PR. I found two major bugs :
> > > > 
> > > > 1. The upload page after uploading the profile do not redirect us back to home.
> > > > 2. If a user already has profile it was not showing it on the home page.
> > > >    I fixed these two by makings some changes on views.py and welcome.html.
> > > 
> > > 
> > > Why would the user be redirected to the home?
> > 
> > 
> > To see his posts and new profile picture. Is this not what happens when we upload our profile picture on instagram.
> 
> When we upload a profile picture, we are redirected to the profile page, not the home page. There is a difference between the home page and the profile page.
> 
> In the future, when we have a profile page, we will add the functionality of redirecting to the profile page, but for now, this will work fine.

Yes, I understand that , also when we are on our home page for now we can upload or change profile pic again but if we do not redirect to home we cannot go back to home as shown in issue #26 .

**Review by abdullah956 — APPROVED** [review]

**Review by muzzammilh — APPROVED** [review]

**Pull request merged**
